/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PeliculasRouteImport } from './routes/peliculas'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as GenerosIndexRouteImport } from './routes/generos/index'
import { Route as GenerosIdRouteImport } from './routes/generos/$id'
import { Route as PeliculaIdRouteImport } from './routes/pelicula/$id'
import { Route as PersonaIdRouteImport } from './routes/persona/$id'
import { Route as SerieIdRouteImport } from './routes/serie/$id'
import { Route as ApiTmdbSplatRouteImport } from './routes/api/tmdb.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PeliculasRoute = PeliculasRouteImport.update({
  id: '/peliculas',
  path: '/peliculas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerosIndexRoute = GenerosIndexRouteImport.update({
  id: '/generos/',
  path: '/generos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerosIdRoute = GenerosIdRouteImport.update({
  id: '/generos/$id',
  path: '/generos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeliculaIdRoute = PeliculaIdRouteImport.update({
  id: '/pelicula/$id',
  path: '/pelicula/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIdRoute = PersonaIdRouteImport.update({
  id: '/persona/$id',
  path: '/persona/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdRoute = SerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbSplatRoute = ApiTmdbSplatRouteImport.update({
  id: '/api/tmdb/$',
  path: '/api/tmdb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/peliculas': typeof PeliculasRoute
  '/privacidad': typeof PrivacidadRoute
  '/series': typeof SeriesRoute
  '/terminos': typeof TerminosRoute
  '/generos/$id': typeof GenerosIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/generos/': typeof GenerosIndexRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/peliculas': typeof PeliculasRoute
  '/privacidad': typeof PrivacidadRoute
  '/series': typeof SeriesRoute
  '/terminos': typeof TerminosRoute
  '/generos/$id': typeof GenerosIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/generos': typeof GenerosIndexRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/peliculas': typeof PeliculasRoute
  '/privacidad': typeof PrivacidadRoute
  '/series': typeof SeriesRoute
  '/terminos': typeof TerminosRoute
  '/generos/$id': typeof GenerosIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/generos/': typeof GenerosIndexRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/cookies'
    | '/favoritos'
    | '/peliculas'
    | '/privacidad'
    | '/series'
    | '/terminos'
    | '/generos/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/generos/'
    | '/api/tmdb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/cookies'
    | '/favoritos'
    | '/peliculas'
    | '/privacidad'
    | '/series'
    | '/terminos'
    | '/generos/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/generos'
    | '/api/tmdb/$'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/cookies'
    | '/favoritos'
    | '/peliculas'
    | '/privacidad'
    | '/series'
    | '/terminos'
    | '/generos/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/generos/'
    | '/api/tmdb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BuscarRoute: typeof BuscarRoute
  CookiesRoute: typeof CookiesRoute
  FavoritosRoute: typeof FavoritosRoute
  PeliculasRoute: typeof PeliculasRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SeriesRoute: typeof SeriesRoute
  TerminosRoute: typeof TerminosRoute
  GenerosIdRoute: typeof GenerosIdRoute
  PeliculaIdRoute: typeof PeliculaIdRoute
  PersonaIdRoute: typeof PersonaIdRoute
  SerieIdRoute: typeof SerieIdRoute
  GenerosIndexRoute: typeof GenerosIndexRoute
  ApiTmdbSplatRoute: typeof ApiTmdbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peliculas': {
      id: '/peliculas'
      path: '/peliculas'
      fullPath: '/peliculas'
      preLoaderRoute: typeof PeliculasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generos/': {
      id: '/generos/'
      path: '/generos'
      fullPath: '/generos/'
      preLoaderRoute: typeof GenerosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generos/$id': {
      id: '/generos/$id'
      path: '/generos/$id'
      fullPath: '/generos/$id'
      preLoaderRoute: typeof GenerosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelicula/$id': {
      id: '/pelicula/$id'
      path: '/pelicula/$id'
      fullPath: '/pelicula/$id'
      preLoaderRoute: typeof PeliculaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$id': {
      id: '/persona/$id'
      path: '/persona/$id'
      fullPath: '/persona/$id'
      preLoaderRoute: typeof PersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id': {
      id: '/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof SerieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/$': {
      id: '/api/tmdb/$'
      path: '/api/tmdb/$'
      fullPath: '/api/tmdb/$'
      preLoaderRoute: typeof ApiTmdbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BuscarRoute: BuscarRoute,
  CookiesRoute: CookiesRoute,
  FavoritosRoute: FavoritosRoute,
  PeliculasRoute: PeliculasRoute,
  PrivacidadRoute: PrivacidadRoute,
  SeriesRoute: SeriesRoute,
  TerminosRoute: TerminosRoute,
  GenerosIdRoute: GenerosIdRoute,
  PeliculaIdRoute: PeliculaIdRoute,
  PersonaIdRoute: PersonaIdRoute,
  SerieIdRoute: SerieIdRoute,
  GenerosIndexRoute: GenerosIndexRoute,
  ApiTmdbSplatRoute: ApiTmdbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
